const assert=require('assert/strict');const {ethers,network}=require('hardhat');const zk=require('../../scripts/zk.cjs');
describe('PrivLedger real Groth16 lifecycle',function(){
 let ledger,owner,outsider,epoch,expiry,c,p;const id=ethers.id('evidence A'),child=ethers.id('redacted A'),secret='123456789012345678901234567890';
 async function register(e=id,cid='bafy-encrypted-test'){return ledger.registerEvidence(e,ethers.id('sha'),ethers.id('keccak'),ethers.ZeroHash,cid,0,ethers.id('pseudonym'));}
 async function access(proof=p,e=id,action=1){const r=await(await ledger.requestAccess(e,action,proof.credentialCommitment,proof.nullifierHash,proof.proof)).wait();return ledger.interface.parseLog(r.logs[0]).args.allowed;}
 before(async()=>{[owner,outsider]=await ethers.getSigners();epoch=Math.floor((await ethers.provider.getBlock('latest')).timestamp/86400);expiry=epoch+365;c=await zk.commitment(secret,1,expiry);p=await zk.prove({secret,role:1,expiry,evidenceId:id,action:1,epoch});});
 beforeEach(async()=>{const v=await(await ethers.getContractFactory('Groth16Verifier')).deploy();const a=await(await ethers.getContractFactory('ZKAdapter')).deploy(await v.getAddress());ledger=await(await ethers.getContractFactory('PrivLedger')).deploy(await a.getAddress());await ledger.issueCredential(c,1,expiry);await register();});
 it('deploys and registers immutable anchors with correct event',async()=>{const e=await ledger.evidence(id);assert.equal(e.state,1n);assert.equal(e.sha256Digest,ethers.id('sha'));const events=await ledger.queryFilter(ledger.filters.EvidenceRegistered());assert.equal(events.length,1);assert.equal(events[0].args.evidenceId,id);});
 it('rejects duplicate registration',async()=>{await assert.rejects(register(),/duplicate/);});
 it('real valid proof verifies off-chain and on-chain, authorizes access',async()=>{assert(p.valid);assert(await ledger.verifyProof(await ledger.CIRCUIT_ID(),p.publicSignals,p.proof));assert(await access());});
 it('rejects replay but preserves audit event',async()=>{assert(await access());assert.equal(await access(),false);assert.equal((await ledger.queryFilter(ledger.filters.AccessDecision())).length,2);});
 it('rejects unknown evidence',async()=>{assert.equal(await access(p,ethers.id('unknown')),false);});
 it('binds evidence and action public inputs',async()=>{await register(child);assert.equal(await access(p,child),false);assert.equal(await access(p,id,2),false);});
 it('denies revoked credential',async()=>{await ledger.revokeCredential(c,ethers.id('reason'));assert.equal(await access(),false);});
 it('denies malformed and altered proofs',async()=>{assert.equal(await access({...p,proof:'0x12'}),false);const altered='0x'+('0'.repeat(64))+p.proof.slice(66);assert.equal(await access({...p,proof:altered}),false);});
 it('rejects altered public signal',async()=>{const signals=[...p.publicSignals];signals[3]=(BigInt(signals[3])+1n).toString();assert.equal(await ledger.verifyProof(await ledger.CIRCUIT_ID(),signals,p.proof),false);});
 it('wrong secret fails witness',async()=>{await assert.rejects(zk.prove({secret:'1',role:1,expiry,evidenceId:id,epoch,credentialCommitment:c}));});
 it('wrong role fails witness',async()=>{await assert.rejects(zk.prove({secret,role:1,requiredRole:2,expiry,evidenceId:id,epoch}));});
 it('expired credential fails witness',async()=>{await assert.rejects(zk.prove({secret,role:1,expiry:epoch-1,evidenceId:id,epoch}));});
 it('unissued commitment never grants access',async()=>{const q=await zk.prove({secret:'987654321',role:1,expiry,evidenceId:id,epoch});assert.equal(await access(q),false);});
 it('protects registration, issuance, revocation, redaction and deletion roles',async()=>{const x=ledger.connect(outsider);await assert.rejects(x.registerEvidence(child,ethers.id('s'),ethers.id('k'),ethers.ZeroHash,'cid',0,ethers.ZeroHash));await assert.rejects(x.issueCredential(ethers.id('x'),1,expiry));await assert.rejects(x.revokeCredential(c,ethers.ZeroHash));await assert.rejects(x.recordRedaction(id,child,'cid',ethers.id('a'),ethers.id('p')));await assert.rejects(x.recordDeletion(id,ethers.id('a'),ethers.id('p')));});
 it('records child lineage and disables access to redacted parent',async()=>{await register(child,'child-cid');await ledger.recordRedaction(id,child,'child-cid',ethers.id('attestation'),ethers.id('proof'));assert.equal((await ledger.evidence(child)).parent,id);assert.equal((await ledger.evidence(id)).state,2n);assert.equal(await access(),false);});
 it('rejects unknown redaction parent and incorrect child CID',async()=>{await register(child);await assert.rejects(ledger.recordRedaction(ethers.id('missing'),child,'bafy-encrypted-test',ethers.id('a'),ethers.id('p')),/parent inactive/);await assert.rejects(ledger.recordRedaction(id,child,'wrong',ethers.id('a'),ethers.id('p')),/cid/);});
 it('records deletion once, retains anchors, denies subsequent access',async()=>{await ledger.recordDeletion(id,ethers.id('attestation'),ethers.id('proof'));assert.equal((await ledger.evidence(id)).state,3n);assert.equal((await ledger.evidence(id)).sha256Digest,ethers.id('sha'));assert.equal(await access(),false);await assert.rejects(ledger.recordDeletion(id,ethers.id('a'),ethers.id('p')),/inactive/);});
 it('pausing stops registration and access',async()=>{await ledger.pause(true);await assert.rejects(register(child));await assert.rejects(access());await ledger.pause(false);assert(await access());});
 it('chain epoch expiry is enforced',async()=>{await network.provider.send('evm_setNextBlockTimestamp',[(expiry+1)*86400]);await network.provider.send('evm_mine');assert.equal(await access(),false);});
});
